# Site settings
title: 生物知识个人分享
SEOTitle: 生物知识个人分享
header-img: img/post-bg-unix-linux.jpg
email: zd200572@gmail.com
description: "关于科技，生物信息与环保 | 赵加栋，Web & Bioinformatics Lover，Microbiome Engineer | 这里是 @zd200572 的个人博客，与你一起发现更大的世界。"
keyword: "加栋, JD加栋, JD, zd200572, @zd200572, 赵加栋的博客, 博客, 个人网站, 互联网, 微生物, 生物信息, Python"
url: "https://zd200572.com"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'



# SNS settings
RSS: true
weibo_username:     zd200572
zhihu_username:     zd200572
github_username:    zd200572
twitter_username:   zd200572
facebook_username:  zd200572
linkedin_username: zd200572-dong-3271687b



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
disqus_username: disqus_xXRUpoMAUT

# Netease setttings
netease_comment: false



# Analytics settings
# Baidu Analytics 
ba_track_id: 898007b8a554ffc70c84d210a4fcd7eb
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: 'UA-105630331-1'            # Format: UA-xxxxxx-xx
ga_domain: zd200572.com



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "快乐生活，好好学习，<br>离开世界之前，一切都是过程"
sidebar-avatar: /img/avatar-JD.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
         title: "生信菜鸟团",
         href: "http://www.bio-info-trainee.com/"
     },{
        title: "生信客部落",
        href: "http://www.bio-info-club.com/"
    },{
        title: "rabbit gao's blog",
        href: "http://www.iwhgao.com/"
    },{
        title: "沈梦圆博客",
        href: "http://shemy.site/"
    },{
        title: "徐洲更简书",
        href: "http://www.jianshu.com/u/9ea40b5f607a"
    },{
        title: "会思考的熊",
        href: "http://kaopubear.top/"
    },{
        title: "生物日志|鸣一道 ",
        href: "http://www.zilhua.com/"
    },{
        title: "hope博客",
        href: "http://tiramisutes.github.io/"
    },{
        title: "陈连福博客",
        href: "http://www.chenlianfu.com/"
    },{
        title: "铁汉1990",
        href: "http://blog.sina.com.cn/tiehan1990"
    },{
        title: "biochen生物",
        href: "http://blog.biochen.com/"
    }
]
